#include <string>

extern std::string halo3_maps[] = {

    "005_intro.map",
    "010_jungle.map",
    "020_base.map",
    "030_outskirts.map",
    "040_voi.map",
    "050_floodvoi.map",
    "070_waste.map",
    "100_citadel.map",
    "110_hc.map",
    "120_halo.map",
    "130_epilogue.map",
    "armory.map",
    "bunkerworld.map",
    "campaign.map",
    "chill.map",
    "chillout.map",
    "construct.map",
    "cyberdyne.map",
    "deadlock.map",
    "descent.map",
    "docks.map",
    "fortress.map",
    "ghosttown.map",
    "guardian.map",
    "isolation.map",
    "lockout.map",
    "mainmenu.map",
    "midship.map",
    "riverworld.map",
    "salvation.map",
    "sandbox.map",
    "shared.map",
    "shrine.map",
    "sidewinder.map",
    "snowbound.map",
    "spacecamp.map",
    "warehouse.map",
    "zanzibar.map"

};